name: Test

on:
  push:
    branches: ["*"]
    tags-ignore: ["*"]
  pull_request:
    branches: ["*"]

  workflow_dispatch:
    inputs:
      logLevel:
        description: Log Level
        default: info
        type: choice
        options:
          - debug
          - error
          - fatal
          - info
          - panic
          - warning
      environment:
        description: Environment
        default: test

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: PostgreSQL packages
        run: |
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          echo "deb http://apt.postgresql.org/pub/repos/apt `lsb_release -cs`-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list
          sudo apt update
          sudo apt install libpq-dev cmake -y

      - name: Run Tests
        run: |
          POSTGRES_VERSION=15
          sudo apt-get install -y --no-install-recommends git build-essential ca-certificates libcurl4-openssl-dev libjson-c-dev postgresql-server-dev-${POSTGRES_VERSION}
          cd src/
          make
          make install
